server:
  port: 8000

database:
  host: 127.0.0.1
  port: 5432
  database: beego
  username: beego
  password: Abc123++

redis:
  host: 127.0.0.1
  port: 6379
  database: 3
  password: QAZwsx123++

jwt:
  secret: Zjuici888***
  sign: Zjuici
